#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     O código foi gerado por uma ferramenta.
//     Versão de Tempo de Execução:4.0.30319.42000
//
//     As alterações ao arquivo poderão causar comportamento incorreto e serão perdidas se
//     o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Estoques.DAL
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="db_estoques")]
	public partial class EstoqueDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void Inserttb_categoria(tb_categoria instance);
    partial void Updatetb_categoria(tb_categoria instance);
    partial void Deletetb_categoria(tb_categoria instance);
    partial void Inserttb_entradasProduto(tb_entradasProduto instance);
    partial void Updatetb_entradasProduto(tb_entradasProduto instance);
    partial void Deletetb_entradasProduto(tb_entradasProduto instance);
    partial void Inserttb_itens_venda(tb_itens_venda instance);
    partial void Updatetb_itens_venda(tb_itens_venda instance);
    partial void Deletetb_itens_venda(tb_itens_venda instance);
    partial void Inserttb_pessoa(tb_pessoa instance);
    partial void Updatetb_pessoa(tb_pessoa instance);
    partial void Deletetb_pessoa(tb_pessoa instance);
    partial void Inserttb_pessoa_fisica(tb_pessoa_fisica instance);
    partial void Updatetb_pessoa_fisica(tb_pessoa_fisica instance);
    partial void Deletetb_pessoa_fisica(tb_pessoa_fisica instance);
    partial void Inserttb_pessoa_juridica(tb_pessoa_juridica instance);
    partial void Updatetb_pessoa_juridica(tb_pessoa_juridica instance);
    partial void Deletetb_pessoa_juridica(tb_pessoa_juridica instance);
    partial void Inserttb_produto(tb_produto instance);
    partial void Updatetb_produto(tb_produto instance);
    partial void Deletetb_produto(tb_produto instance);
    partial void Inserttb_saidasProduto(tb_saidasProduto instance);
    partial void Updatetb_saidasProduto(tb_saidasProduto instance);
    partial void Deletetb_saidasProduto(tb_saidasProduto instance);
    partial void Inserttb_usuario(tb_usuario instance);
    partial void Updatetb_usuario(tb_usuario instance);
    partial void Deletetb_usuario(tb_usuario instance);
    partial void Inserttb_venda(tb_venda instance);
    partial void Updatetb_venda(tb_venda instance);
    partial void Deletetb_venda(tb_venda instance);
    #endregion
		
		public EstoqueDataContext() : 
				base(global::Estoques.DAL.Properties.Settings.Default.db_estoquesConnectionString1, mappingSource)
		{
			OnCreated();
		}
		
		public EstoqueDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public EstoqueDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public EstoqueDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public EstoqueDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<tb_categoria> tb_categoria
		{
			get
			{
				return this.GetTable<tb_categoria>();
			}
		}
		
		public System.Data.Linq.Table<tb_entradasProduto> tb_entradasProduto
		{
			get
			{
				return this.GetTable<tb_entradasProduto>();
			}
		}
		
		public System.Data.Linq.Table<tb_itens_venda> tb_itens_venda
		{
			get
			{
				return this.GetTable<tb_itens_venda>();
			}
		}
		
		public System.Data.Linq.Table<tb_pessoa> tb_pessoa
		{
			get
			{
				return this.GetTable<tb_pessoa>();
			}
		}
		
		public System.Data.Linq.Table<tb_pessoa_fisica> tb_pessoa_fisica
		{
			get
			{
				return this.GetTable<tb_pessoa_fisica>();
			}
		}
		
		public System.Data.Linq.Table<tb_pessoa_juridica> tb_pessoa_juridica
		{
			get
			{
				return this.GetTable<tb_pessoa_juridica>();
			}
		}
		
		public System.Data.Linq.Table<tb_produto> tb_produto
		{
			get
			{
				return this.GetTable<tb_produto>();
			}
		}
		
		public System.Data.Linq.Table<tb_saidasProduto> tb_saidasProduto
		{
			get
			{
				return this.GetTable<tb_saidasProduto>();
			}
		}
		
		public System.Data.Linq.Table<tb_usuario> tb_usuario
		{
			get
			{
				return this.GetTable<tb_usuario>();
			}
		}
		
		public System.Data.Linq.Table<tb_venda> tb_venda
		{
			get
			{
				return this.GetTable<tb_venda>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tb_categoria")]
	public partial class tb_categoria : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id_categoria;
		
		private string _ds_categoria;
		
		private EntitySet<tb_produto> _tb_produto;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onid_categoriaChanging(int value);
    partial void Onid_categoriaChanged();
    partial void Onds_categoriaChanging(string value);
    partial void Onds_categoriaChanged();
    #endregion
		
		public tb_categoria()
		{
			this._tb_produto = new EntitySet<tb_produto>(new Action<tb_produto>(this.attach_tb_produto), new Action<tb_produto>(this.detach_tb_produto));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_categoria", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id_categoria
		{
			get
			{
				return this._id_categoria;
			}
			set
			{
				if ((this._id_categoria != value))
				{
					this.Onid_categoriaChanging(value);
					this.SendPropertyChanging();
					this._id_categoria = value;
					this.SendPropertyChanged("id_categoria");
					this.Onid_categoriaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ds_categoria", DbType="VarChar(50)")]
		public string ds_categoria
		{
			get
			{
				return this._ds_categoria;
			}
			set
			{
				if ((this._ds_categoria != value))
				{
					this.Onds_categoriaChanging(value);
					this.SendPropertyChanging();
					this._ds_categoria = value;
					this.SendPropertyChanged("ds_categoria");
					this.Onds_categoriaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tb_categoria_tb_produto", Storage="_tb_produto", ThisKey="id_categoria", OtherKey="id_categoria")]
		public EntitySet<tb_produto> tb_produto
		{
			get
			{
				return this._tb_produto;
			}
			set
			{
				this._tb_produto.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_tb_produto(tb_produto entity)
		{
			this.SendPropertyChanging();
			entity.tb_categoria = this;
		}
		
		private void detach_tb_produto(tb_produto entity)
		{
			this.SendPropertyChanging();
			entity.tb_categoria = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tb_entradasProduto")]
	public partial class tb_entradasProduto : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id_entrada;
		
		private System.Nullable<int> _qtdEtrada;
		
		private System.Nullable<int> _id_produto;
		
		private System.Nullable<int> _qtdAnterior;
		
		private string _data;
		
		private System.Nullable<int> _valorCompra;
		
		private System.Nullable<int> _CodigoBarras;
		
		private EntityRef<tb_produto> _tb_produto;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onid_entradaChanging(int value);
    partial void Onid_entradaChanged();
    partial void OnqtdEtradaChanging(System.Nullable<int> value);
    partial void OnqtdEtradaChanged();
    partial void Onid_produtoChanging(System.Nullable<int> value);
    partial void Onid_produtoChanged();
    partial void OnqtdAnteriorChanging(System.Nullable<int> value);
    partial void OnqtdAnteriorChanged();
    partial void OndataChanging(string value);
    partial void OndataChanged();
    partial void OnvalorCompraChanging(System.Nullable<int> value);
    partial void OnvalorCompraChanged();
    partial void OnCodigoBarrasChanging(System.Nullable<int> value);
    partial void OnCodigoBarrasChanged();
    #endregion
		
		public tb_entradasProduto()
		{
			this._tb_produto = default(EntityRef<tb_produto>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_entrada", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id_entrada
		{
			get
			{
				return this._id_entrada;
			}
			set
			{
				if ((this._id_entrada != value))
				{
					this.Onid_entradaChanging(value);
					this.SendPropertyChanging();
					this._id_entrada = value;
					this.SendPropertyChanged("id_entrada");
					this.Onid_entradaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_qtdEtrada", DbType="Int")]
		public System.Nullable<int> qtdEtrada
		{
			get
			{
				return this._qtdEtrada;
			}
			set
			{
				if ((this._qtdEtrada != value))
				{
					this.OnqtdEtradaChanging(value);
					this.SendPropertyChanging();
					this._qtdEtrada = value;
					this.SendPropertyChanged("qtdEtrada");
					this.OnqtdEtradaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_produto", DbType="Int")]
		public System.Nullable<int> id_produto
		{
			get
			{
				return this._id_produto;
			}
			set
			{
				if ((this._id_produto != value))
				{
					if (this._tb_produto.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Onid_produtoChanging(value);
					this.SendPropertyChanging();
					this._id_produto = value;
					this.SendPropertyChanged("id_produto");
					this.Onid_produtoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_qtdAnterior", DbType="Int")]
		public System.Nullable<int> qtdAnterior
		{
			get
			{
				return this._qtdAnterior;
			}
			set
			{
				if ((this._qtdAnterior != value))
				{
					this.OnqtdAnteriorChanging(value);
					this.SendPropertyChanging();
					this._qtdAnterior = value;
					this.SendPropertyChanged("qtdAnterior");
					this.OnqtdAnteriorChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_data", DbType="VarChar(50)")]
		public string data
		{
			get
			{
				return this._data;
			}
			set
			{
				if ((this._data != value))
				{
					this.OndataChanging(value);
					this.SendPropertyChanging();
					this._data = value;
					this.SendPropertyChanged("data");
					this.OndataChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_valorCompra", DbType="Int")]
		public System.Nullable<int> valorCompra
		{
			get
			{
				return this._valorCompra;
			}
			set
			{
				if ((this._valorCompra != value))
				{
					this.OnvalorCompraChanging(value);
					this.SendPropertyChanging();
					this._valorCompra = value;
					this.SendPropertyChanged("valorCompra");
					this.OnvalorCompraChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CodigoBarras", DbType="Int")]
		public System.Nullable<int> CodigoBarras
		{
			get
			{
				return this._CodigoBarras;
			}
			set
			{
				if ((this._CodigoBarras != value))
				{
					this.OnCodigoBarrasChanging(value);
					this.SendPropertyChanging();
					this._CodigoBarras = value;
					this.SendPropertyChanged("CodigoBarras");
					this.OnCodigoBarrasChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tb_produto_tb_entradasProduto", Storage="_tb_produto", ThisKey="id_produto", OtherKey="id_produto", IsForeignKey=true)]
		public tb_produto tb_produto
		{
			get
			{
				return this._tb_produto.Entity;
			}
			set
			{
				tb_produto previousValue = this._tb_produto.Entity;
				if (((previousValue != value) 
							|| (this._tb_produto.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._tb_produto.Entity = null;
						previousValue.tb_entradasProduto.Remove(this);
					}
					this._tb_produto.Entity = value;
					if ((value != null))
					{
						value.tb_entradasProduto.Add(this);
						this._id_produto = value.id_produto;
					}
					else
					{
						this._id_produto = default(Nullable<int>);
					}
					this.SendPropertyChanged("tb_produto");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tb_itens_venda")]
	public partial class tb_itens_venda : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _quantidade;
		
		private int _id_produto;
		
		private int _id_venda;
		
		private decimal _valor;
		
		private int _id_item;
		
		private EntityRef<tb_produto> _tb_produto;
		
		private EntityRef<tb_venda> _tb_venda;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnquantidadeChanging(int value);
    partial void OnquantidadeChanged();
    partial void Onid_produtoChanging(int value);
    partial void Onid_produtoChanged();
    partial void Onid_vendaChanging(int value);
    partial void Onid_vendaChanged();
    partial void OnvalorChanging(decimal value);
    partial void OnvalorChanged();
    partial void Onid_itemChanging(int value);
    partial void Onid_itemChanged();
    #endregion
		
		public tb_itens_venda()
		{
			this._tb_produto = default(EntityRef<tb_produto>);
			this._tb_venda = default(EntityRef<tb_venda>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_quantidade", DbType="Int NOT NULL")]
		public int quantidade
		{
			get
			{
				return this._quantidade;
			}
			set
			{
				if ((this._quantidade != value))
				{
					this.OnquantidadeChanging(value);
					this.SendPropertyChanging();
					this._quantidade = value;
					this.SendPropertyChanged("quantidade");
					this.OnquantidadeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_produto", DbType="Int NOT NULL")]
		public int id_produto
		{
			get
			{
				return this._id_produto;
			}
			set
			{
				if ((this._id_produto != value))
				{
					if (this._tb_produto.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Onid_produtoChanging(value);
					this.SendPropertyChanging();
					this._id_produto = value;
					this.SendPropertyChanged("id_produto");
					this.Onid_produtoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_venda", DbType="Int NOT NULL")]
		public int id_venda
		{
			get
			{
				return this._id_venda;
			}
			set
			{
				if ((this._id_venda != value))
				{
					if (this._tb_venda.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Onid_vendaChanging(value);
					this.SendPropertyChanging();
					this._id_venda = value;
					this.SendPropertyChanged("id_venda");
					this.Onid_vendaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_valor", DbType="Decimal(15,2) NOT NULL")]
		public decimal valor
		{
			get
			{
				return this._valor;
			}
			set
			{
				if ((this._valor != value))
				{
					this.OnvalorChanging(value);
					this.SendPropertyChanging();
					this._valor = value;
					this.SendPropertyChanged("valor");
					this.OnvalorChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_item", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id_item
		{
			get
			{
				return this._id_item;
			}
			set
			{
				if ((this._id_item != value))
				{
					this.Onid_itemChanging(value);
					this.SendPropertyChanging();
					this._id_item = value;
					this.SendPropertyChanged("id_item");
					this.Onid_itemChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tb_produto_tb_itens_venda", Storage="_tb_produto", ThisKey="id_produto", OtherKey="id_produto", IsForeignKey=true)]
		public tb_produto tb_produto
		{
			get
			{
				return this._tb_produto.Entity;
			}
			set
			{
				tb_produto previousValue = this._tb_produto.Entity;
				if (((previousValue != value) 
							|| (this._tb_produto.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._tb_produto.Entity = null;
						previousValue.tb_itens_venda.Remove(this);
					}
					this._tb_produto.Entity = value;
					if ((value != null))
					{
						value.tb_itens_venda.Add(this);
						this._id_produto = value.id_produto;
					}
					else
					{
						this._id_produto = default(int);
					}
					this.SendPropertyChanged("tb_produto");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tb_venda_tb_itens_venda", Storage="_tb_venda", ThisKey="id_venda", OtherKey="id_venda", IsForeignKey=true)]
		public tb_venda tb_venda
		{
			get
			{
				return this._tb_venda.Entity;
			}
			set
			{
				tb_venda previousValue = this._tb_venda.Entity;
				if (((previousValue != value) 
							|| (this._tb_venda.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._tb_venda.Entity = null;
						previousValue.tb_itens_venda.Remove(this);
					}
					this._tb_venda.Entity = value;
					if ((value != null))
					{
						value.tb_itens_venda.Add(this);
						this._id_venda = value.id_venda;
					}
					else
					{
						this._id_venda = default(int);
					}
					this.SendPropertyChanged("tb_venda");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tb_pessoa")]
	public partial class tb_pessoa : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id_pessoa;
		
		private string _nome;
		
		private string _telefone;
		
		private string _email;
		
		private EntityRef<tb_pessoa_fisica> _tb_pessoa_fisica;
		
		private EntityRef<tb_pessoa_juridica> _tb_pessoa_juridica;
		
		private EntityRef<tb_usuario> _tb_usuario;
		
		private EntitySet<tb_venda> _tb_venda;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onid_pessoaChanging(int value);
    partial void Onid_pessoaChanged();
    partial void OnnomeChanging(string value);
    partial void OnnomeChanged();
    partial void OntelefoneChanging(string value);
    partial void OntelefoneChanged();
    partial void OnemailChanging(string value);
    partial void OnemailChanged();
    #endregion
		
		public tb_pessoa()
		{
			this._tb_pessoa_fisica = default(EntityRef<tb_pessoa_fisica>);
			this._tb_pessoa_juridica = default(EntityRef<tb_pessoa_juridica>);
			this._tb_usuario = default(EntityRef<tb_usuario>);
			this._tb_venda = new EntitySet<tb_venda>(new Action<tb_venda>(this.attach_tb_venda), new Action<tb_venda>(this.detach_tb_venda));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_pessoa", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id_pessoa
		{
			get
			{
				return this._id_pessoa;
			}
			set
			{
				if ((this._id_pessoa != value))
				{
					this.Onid_pessoaChanging(value);
					this.SendPropertyChanging();
					this._id_pessoa = value;
					this.SendPropertyChanged("id_pessoa");
					this.Onid_pessoaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nome", DbType="VarChar(200) NOT NULL", CanBeNull=false)]
		public string nome
		{
			get
			{
				return this._nome;
			}
			set
			{
				if ((this._nome != value))
				{
					this.OnnomeChanging(value);
					this.SendPropertyChanging();
					this._nome = value;
					this.SendPropertyChanged("nome");
					this.OnnomeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_telefone", DbType="VarChar(30)")]
		public string telefone
		{
			get
			{
				return this._telefone;
			}
			set
			{
				if ((this._telefone != value))
				{
					this.OntelefoneChanging(value);
					this.SendPropertyChanging();
					this._telefone = value;
					this.SendPropertyChanged("telefone");
					this.OntelefoneChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_email", DbType="VarChar(200)")]
		public string email
		{
			get
			{
				return this._email;
			}
			set
			{
				if ((this._email != value))
				{
					this.OnemailChanging(value);
					this.SendPropertyChanging();
					this._email = value;
					this.SendPropertyChanged("email");
					this.OnemailChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tb_pessoa_tb_pessoa_fisica", Storage="_tb_pessoa_fisica", ThisKey="id_pessoa", OtherKey="id_pessoa", IsUnique=true, IsForeignKey=false)]
		public tb_pessoa_fisica tb_pessoa_fisica
		{
			get
			{
				return this._tb_pessoa_fisica.Entity;
			}
			set
			{
				tb_pessoa_fisica previousValue = this._tb_pessoa_fisica.Entity;
				if (((previousValue != value) 
							|| (this._tb_pessoa_fisica.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._tb_pessoa_fisica.Entity = null;
						previousValue.tb_pessoa = null;
					}
					this._tb_pessoa_fisica.Entity = value;
					if ((value != null))
					{
						value.tb_pessoa = this;
					}
					this.SendPropertyChanged("tb_pessoa_fisica");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tb_pessoa_tb_pessoa_juridica", Storage="_tb_pessoa_juridica", ThisKey="id_pessoa", OtherKey="id_pessoa", IsUnique=true, IsForeignKey=false)]
		public tb_pessoa_juridica tb_pessoa_juridica
		{
			get
			{
				return this._tb_pessoa_juridica.Entity;
			}
			set
			{
				tb_pessoa_juridica previousValue = this._tb_pessoa_juridica.Entity;
				if (((previousValue != value) 
							|| (this._tb_pessoa_juridica.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._tb_pessoa_juridica.Entity = null;
						previousValue.tb_pessoa = null;
					}
					this._tb_pessoa_juridica.Entity = value;
					if ((value != null))
					{
						value.tb_pessoa = this;
					}
					this.SendPropertyChanged("tb_pessoa_juridica");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tb_pessoa_tb_usuario", Storage="_tb_usuario", ThisKey="id_pessoa", OtherKey="id_pessoa", IsUnique=true, IsForeignKey=false)]
		public tb_usuario tb_usuario
		{
			get
			{
				return this._tb_usuario.Entity;
			}
			set
			{
				tb_usuario previousValue = this._tb_usuario.Entity;
				if (((previousValue != value) 
							|| (this._tb_usuario.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._tb_usuario.Entity = null;
						previousValue.tb_pessoa = null;
					}
					this._tb_usuario.Entity = value;
					if ((value != null))
					{
						value.tb_pessoa = this;
					}
					this.SendPropertyChanged("tb_usuario");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tb_pessoa_tb_venda", Storage="_tb_venda", ThisKey="id_pessoa", OtherKey="id_pessoa")]
		public EntitySet<tb_venda> tb_venda
		{
			get
			{
				return this._tb_venda;
			}
			set
			{
				this._tb_venda.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_tb_venda(tb_venda entity)
		{
			this.SendPropertyChanging();
			entity.tb_pessoa = this;
		}
		
		private void detach_tb_venda(tb_venda entity)
		{
			this.SendPropertyChanging();
			entity.tb_pessoa = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tb_pessoa_fisica")]
	public partial class tb_pessoa_fisica : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _cpf;
		
		private string _rg;
		
		private System.Nullable<System.DateTime> _data_nascimento;
		
		private string _pai;
		
		private string _mae;
		
		private int _id_pessoa;
		
		private EntityRef<tb_pessoa> _tb_pessoa;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OncpfChanging(string value);
    partial void OncpfChanged();
    partial void OnrgChanging(string value);
    partial void OnrgChanged();
    partial void Ondata_nascimentoChanging(System.Nullable<System.DateTime> value);
    partial void Ondata_nascimentoChanged();
    partial void OnpaiChanging(string value);
    partial void OnpaiChanged();
    partial void OnmaeChanging(string value);
    partial void OnmaeChanged();
    partial void Onid_pessoaChanging(int value);
    partial void Onid_pessoaChanged();
    #endregion
		
		public tb_pessoa_fisica()
		{
			this._tb_pessoa = default(EntityRef<tb_pessoa>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cpf", DbType="VarChar(20) NOT NULL", CanBeNull=false)]
		public string cpf
		{
			get
			{
				return this._cpf;
			}
			set
			{
				if ((this._cpf != value))
				{
					this.OncpfChanging(value);
					this.SendPropertyChanging();
					this._cpf = value;
					this.SendPropertyChanged("cpf");
					this.OncpfChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_rg", DbType="VarChar(20) NOT NULL", CanBeNull=false)]
		public string rg
		{
			get
			{
				return this._rg;
			}
			set
			{
				if ((this._rg != value))
				{
					this.OnrgChanging(value);
					this.SendPropertyChanging();
					this._rg = value;
					this.SendPropertyChanged("rg");
					this.OnrgChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_data_nascimento", DbType="Date")]
		public System.Nullable<System.DateTime> data_nascimento
		{
			get
			{
				return this._data_nascimento;
			}
			set
			{
				if ((this._data_nascimento != value))
				{
					this.Ondata_nascimentoChanging(value);
					this.SendPropertyChanging();
					this._data_nascimento = value;
					this.SendPropertyChanged("data_nascimento");
					this.Ondata_nascimentoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_pai", DbType="VarChar(200)")]
		public string pai
		{
			get
			{
				return this._pai;
			}
			set
			{
				if ((this._pai != value))
				{
					this.OnpaiChanging(value);
					this.SendPropertyChanging();
					this._pai = value;
					this.SendPropertyChanged("pai");
					this.OnpaiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_mae", DbType="VarChar(200)")]
		public string mae
		{
			get
			{
				return this._mae;
			}
			set
			{
				if ((this._mae != value))
				{
					this.OnmaeChanging(value);
					this.SendPropertyChanging();
					this._mae = value;
					this.SendPropertyChanged("mae");
					this.OnmaeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_pessoa", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int id_pessoa
		{
			get
			{
				return this._id_pessoa;
			}
			set
			{
				if ((this._id_pessoa != value))
				{
					if (this._tb_pessoa.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Onid_pessoaChanging(value);
					this.SendPropertyChanging();
					this._id_pessoa = value;
					this.SendPropertyChanged("id_pessoa");
					this.Onid_pessoaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tb_pessoa_tb_pessoa_fisica", Storage="_tb_pessoa", ThisKey="id_pessoa", OtherKey="id_pessoa", IsForeignKey=true, DeleteOnNull=true, DeleteRule="CASCADE")]
		public tb_pessoa tb_pessoa
		{
			get
			{
				return this._tb_pessoa.Entity;
			}
			set
			{
				tb_pessoa previousValue = this._tb_pessoa.Entity;
				if (((previousValue != value) 
							|| (this._tb_pessoa.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._tb_pessoa.Entity = null;
						previousValue.tb_pessoa_fisica = null;
					}
					this._tb_pessoa.Entity = value;
					if ((value != null))
					{
						value.tb_pessoa_fisica = this;
						this._id_pessoa = value.id_pessoa;
					}
					else
					{
						this._id_pessoa = default(int);
					}
					this.SendPropertyChanged("tb_pessoa");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tb_pessoa_juridica")]
	public partial class tb_pessoa_juridica : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _cnpj;
		
		private string _inscricao;
		
		private string _razao_social;
		
		private int _id_pessoa;
		
		private EntityRef<tb_pessoa> _tb_pessoa;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OncnpjChanging(string value);
    partial void OncnpjChanged();
    partial void OninscricaoChanging(string value);
    partial void OninscricaoChanged();
    partial void Onrazao_socialChanging(string value);
    partial void Onrazao_socialChanged();
    partial void Onid_pessoaChanging(int value);
    partial void Onid_pessoaChanged();
    #endregion
		
		public tb_pessoa_juridica()
		{
			this._tb_pessoa = default(EntityRef<tb_pessoa>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cnpj", DbType="VarChar(30) NOT NULL", CanBeNull=false)]
		public string cnpj
		{
			get
			{
				return this._cnpj;
			}
			set
			{
				if ((this._cnpj != value))
				{
					this.OncnpjChanging(value);
					this.SendPropertyChanging();
					this._cnpj = value;
					this.SendPropertyChanged("cnpj");
					this.OncnpjChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_inscricao", DbType="VarChar(30) NOT NULL", CanBeNull=false)]
		public string inscricao
		{
			get
			{
				return this._inscricao;
			}
			set
			{
				if ((this._inscricao != value))
				{
					this.OninscricaoChanging(value);
					this.SendPropertyChanging();
					this._inscricao = value;
					this.SendPropertyChanged("inscricao");
					this.OninscricaoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_razao_social", DbType="VarChar(200) NOT NULL", CanBeNull=false)]
		public string razao_social
		{
			get
			{
				return this._razao_social;
			}
			set
			{
				if ((this._razao_social != value))
				{
					this.Onrazao_socialChanging(value);
					this.SendPropertyChanging();
					this._razao_social = value;
					this.SendPropertyChanged("razao_social");
					this.Onrazao_socialChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_pessoa", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int id_pessoa
		{
			get
			{
				return this._id_pessoa;
			}
			set
			{
				if ((this._id_pessoa != value))
				{
					if (this._tb_pessoa.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Onid_pessoaChanging(value);
					this.SendPropertyChanging();
					this._id_pessoa = value;
					this.SendPropertyChanged("id_pessoa");
					this.Onid_pessoaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tb_pessoa_tb_pessoa_juridica", Storage="_tb_pessoa", ThisKey="id_pessoa", OtherKey="id_pessoa", IsForeignKey=true)]
		public tb_pessoa tb_pessoa
		{
			get
			{
				return this._tb_pessoa.Entity;
			}
			set
			{
				tb_pessoa previousValue = this._tb_pessoa.Entity;
				if (((previousValue != value) 
							|| (this._tb_pessoa.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._tb_pessoa.Entity = null;
						previousValue.tb_pessoa_juridica = null;
					}
					this._tb_pessoa.Entity = value;
					if ((value != null))
					{
						value.tb_pessoa_juridica = this;
						this._id_pessoa = value.id_pessoa;
					}
					else
					{
						this._id_pessoa = default(int);
					}
					this.SendPropertyChanged("tb_pessoa");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tb_produto")]
	public partial class tb_produto : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id_produto;
		
		private string _ds_produto;
		
		private System.Nullable<decimal> _valor;
		
		private System.Nullable<int> _id_categoria;
		
		private System.Nullable<int> _qtd;
		
		private System.Nullable<long> _CodigoBarras;
		
		private EntitySet<tb_entradasProduto> _tb_entradasProduto;
		
		private EntitySet<tb_itens_venda> _tb_itens_venda;
		
		private EntitySet<tb_saidasProduto> _tb_saidasProduto;
		
		private EntityRef<tb_categoria> _tb_categoria;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onid_produtoChanging(int value);
    partial void Onid_produtoChanged();
    partial void Onds_produtoChanging(string value);
    partial void Onds_produtoChanged();
    partial void OnvalorChanging(System.Nullable<decimal> value);
    partial void OnvalorChanged();
    partial void Onid_categoriaChanging(System.Nullable<int> value);
    partial void Onid_categoriaChanged();
    partial void OnqtdChanging(System.Nullable<int> value);
    partial void OnqtdChanged();
    partial void OnCodigoBarrasChanging(System.Nullable<long> value);
    partial void OnCodigoBarrasChanged();
    #endregion
		
		public tb_produto()
		{
			this._tb_entradasProduto = new EntitySet<tb_entradasProduto>(new Action<tb_entradasProduto>(this.attach_tb_entradasProduto), new Action<tb_entradasProduto>(this.detach_tb_entradasProduto));
			this._tb_itens_venda = new EntitySet<tb_itens_venda>(new Action<tb_itens_venda>(this.attach_tb_itens_venda), new Action<tb_itens_venda>(this.detach_tb_itens_venda));
			this._tb_saidasProduto = new EntitySet<tb_saidasProduto>(new Action<tb_saidasProduto>(this.attach_tb_saidasProduto), new Action<tb_saidasProduto>(this.detach_tb_saidasProduto));
			this._tb_categoria = default(EntityRef<tb_categoria>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_produto", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id_produto
		{
			get
			{
				return this._id_produto;
			}
			set
			{
				if ((this._id_produto != value))
				{
					this.Onid_produtoChanging(value);
					this.SendPropertyChanging();
					this._id_produto = value;
					this.SendPropertyChanged("id_produto");
					this.Onid_produtoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ds_produto", DbType="VarChar(80)")]
		public string ds_produto
		{
			get
			{
				return this._ds_produto;
			}
			set
			{
				if ((this._ds_produto != value))
				{
					this.Onds_produtoChanging(value);
					this.SendPropertyChanging();
					this._ds_produto = value;
					this.SendPropertyChanged("ds_produto");
					this.Onds_produtoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_valor", DbType="Decimal(15,2)")]
		public System.Nullable<decimal> valor
		{
			get
			{
				return this._valor;
			}
			set
			{
				if ((this._valor != value))
				{
					this.OnvalorChanging(value);
					this.SendPropertyChanging();
					this._valor = value;
					this.SendPropertyChanged("valor");
					this.OnvalorChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_categoria", DbType="Int")]
		public System.Nullable<int> id_categoria
		{
			get
			{
				return this._id_categoria;
			}
			set
			{
				if ((this._id_categoria != value))
				{
					if (this._tb_categoria.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Onid_categoriaChanging(value);
					this.SendPropertyChanging();
					this._id_categoria = value;
					this.SendPropertyChanged("id_categoria");
					this.Onid_categoriaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_qtd", DbType="Int")]
		public System.Nullable<int> qtd
		{
			get
			{
				return this._qtd;
			}
			set
			{
				if ((this._qtd != value))
				{
					this.OnqtdChanging(value);
					this.SendPropertyChanging();
					this._qtd = value;
					this.SendPropertyChanged("qtd");
					this.OnqtdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CodigoBarras", DbType="BigInt")]
		public System.Nullable<long> CodigoBarras
		{
			get
			{
				return this._CodigoBarras;
			}
			set
			{
				if ((this._CodigoBarras != value))
				{
					this.OnCodigoBarrasChanging(value);
					this.SendPropertyChanging();
					this._CodigoBarras = value;
					this.SendPropertyChanged("CodigoBarras");
					this.OnCodigoBarrasChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tb_produto_tb_entradasProduto", Storage="_tb_entradasProduto", ThisKey="id_produto", OtherKey="id_produto")]
		public EntitySet<tb_entradasProduto> tb_entradasProduto
		{
			get
			{
				return this._tb_entradasProduto;
			}
			set
			{
				this._tb_entradasProduto.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tb_produto_tb_itens_venda", Storage="_tb_itens_venda", ThisKey="id_produto", OtherKey="id_produto")]
		public EntitySet<tb_itens_venda> tb_itens_venda
		{
			get
			{
				return this._tb_itens_venda;
			}
			set
			{
				this._tb_itens_venda.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tb_produto_tb_saidasProduto", Storage="_tb_saidasProduto", ThisKey="id_produto", OtherKey="id_produto")]
		public EntitySet<tb_saidasProduto> tb_saidasProduto
		{
			get
			{
				return this._tb_saidasProduto;
			}
			set
			{
				this._tb_saidasProduto.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tb_categoria_tb_produto", Storage="_tb_categoria", ThisKey="id_categoria", OtherKey="id_categoria", IsForeignKey=true)]
		public tb_categoria tb_categoria
		{
			get
			{
				return this._tb_categoria.Entity;
			}
			set
			{
				tb_categoria previousValue = this._tb_categoria.Entity;
				if (((previousValue != value) 
							|| (this._tb_categoria.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._tb_categoria.Entity = null;
						previousValue.tb_produto.Remove(this);
					}
					this._tb_categoria.Entity = value;
					if ((value != null))
					{
						value.tb_produto.Add(this);
						this._id_categoria = value.id_categoria;
					}
					else
					{
						this._id_categoria = default(Nullable<int>);
					}
					this.SendPropertyChanged("tb_categoria");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_tb_entradasProduto(tb_entradasProduto entity)
		{
			this.SendPropertyChanging();
			entity.tb_produto = this;
		}
		
		private void detach_tb_entradasProduto(tb_entradasProduto entity)
		{
			this.SendPropertyChanging();
			entity.tb_produto = null;
		}
		
		private void attach_tb_itens_venda(tb_itens_venda entity)
		{
			this.SendPropertyChanging();
			entity.tb_produto = this;
		}
		
		private void detach_tb_itens_venda(tb_itens_venda entity)
		{
			this.SendPropertyChanging();
			entity.tb_produto = null;
		}
		
		private void attach_tb_saidasProduto(tb_saidasProduto entity)
		{
			this.SendPropertyChanging();
			entity.tb_produto = this;
		}
		
		private void detach_tb_saidasProduto(tb_saidasProduto entity)
		{
			this.SendPropertyChanging();
			entity.tb_produto = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tb_saidasProduto")]
	public partial class tb_saidasProduto : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id_saida;
		
		private System.Nullable<int> _qtdSaida;
		
		private System.Nullable<int> _id_produto;
		
		private System.Nullable<int> _qtdAnterior;
		
		private string _data;
		
		private System.Nullable<int> _CodigoDeBarras;
		
		private EntityRef<tb_produto> _tb_produto;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onid_saidaChanging(int value);
    partial void Onid_saidaChanged();
    partial void OnqtdSaidaChanging(System.Nullable<int> value);
    partial void OnqtdSaidaChanged();
    partial void Onid_produtoChanging(System.Nullable<int> value);
    partial void Onid_produtoChanged();
    partial void OnqtdAnteriorChanging(System.Nullable<int> value);
    partial void OnqtdAnteriorChanged();
    partial void OndataChanging(string value);
    partial void OndataChanged();
    partial void OnCodigoDeBarrasChanging(System.Nullable<int> value);
    partial void OnCodigoDeBarrasChanged();
    #endregion
		
		public tb_saidasProduto()
		{
			this._tb_produto = default(EntityRef<tb_produto>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_saida", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id_saida
		{
			get
			{
				return this._id_saida;
			}
			set
			{
				if ((this._id_saida != value))
				{
					this.Onid_saidaChanging(value);
					this.SendPropertyChanging();
					this._id_saida = value;
					this.SendPropertyChanged("id_saida");
					this.Onid_saidaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_qtdSaida", DbType="Int")]
		public System.Nullable<int> qtdSaida
		{
			get
			{
				return this._qtdSaida;
			}
			set
			{
				if ((this._qtdSaida != value))
				{
					this.OnqtdSaidaChanging(value);
					this.SendPropertyChanging();
					this._qtdSaida = value;
					this.SendPropertyChanged("qtdSaida");
					this.OnqtdSaidaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_produto", DbType="Int")]
		public System.Nullable<int> id_produto
		{
			get
			{
				return this._id_produto;
			}
			set
			{
				if ((this._id_produto != value))
				{
					if (this._tb_produto.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Onid_produtoChanging(value);
					this.SendPropertyChanging();
					this._id_produto = value;
					this.SendPropertyChanged("id_produto");
					this.Onid_produtoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_qtdAnterior", DbType="Int")]
		public System.Nullable<int> qtdAnterior
		{
			get
			{
				return this._qtdAnterior;
			}
			set
			{
				if ((this._qtdAnterior != value))
				{
					this.OnqtdAnteriorChanging(value);
					this.SendPropertyChanging();
					this._qtdAnterior = value;
					this.SendPropertyChanged("qtdAnterior");
					this.OnqtdAnteriorChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_data", DbType="VarChar(50)")]
		public string data
		{
			get
			{
				return this._data;
			}
			set
			{
				if ((this._data != value))
				{
					this.OndataChanging(value);
					this.SendPropertyChanging();
					this._data = value;
					this.SendPropertyChanged("data");
					this.OndataChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CodigoDeBarras", DbType="Int")]
		public System.Nullable<int> CodigoDeBarras
		{
			get
			{
				return this._CodigoDeBarras;
			}
			set
			{
				if ((this._CodigoDeBarras != value))
				{
					this.OnCodigoDeBarrasChanging(value);
					this.SendPropertyChanging();
					this._CodigoDeBarras = value;
					this.SendPropertyChanged("CodigoDeBarras");
					this.OnCodigoDeBarrasChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tb_produto_tb_saidasProduto", Storage="_tb_produto", ThisKey="id_produto", OtherKey="id_produto", IsForeignKey=true)]
		public tb_produto tb_produto
		{
			get
			{
				return this._tb_produto.Entity;
			}
			set
			{
				tb_produto previousValue = this._tb_produto.Entity;
				if (((previousValue != value) 
							|| (this._tb_produto.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._tb_produto.Entity = null;
						previousValue.tb_saidasProduto.Remove(this);
					}
					this._tb_produto.Entity = value;
					if ((value != null))
					{
						value.tb_saidasProduto.Add(this);
						this._id_produto = value.id_produto;
					}
					else
					{
						this._id_produto = default(Nullable<int>);
					}
					this.SendPropertyChanged("tb_produto");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tb_usuario")]
	public partial class tb_usuario : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _usuario;
		
		private string _senha;
		
		private int _id_pessoa;
		
		private string _Perfil;
		
		private EntityRef<tb_pessoa> _tb_pessoa;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnusuarioChanging(string value);
    partial void OnusuarioChanged();
    partial void OnsenhaChanging(string value);
    partial void OnsenhaChanged();
    partial void Onid_pessoaChanging(int value);
    partial void Onid_pessoaChanged();
    partial void OnPerfilChanging(string value);
    partial void OnPerfilChanged();
    #endregion
		
		public tb_usuario()
		{
			this._tb_pessoa = default(EntityRef<tb_pessoa>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_usuario", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string usuario
		{
			get
			{
				return this._usuario;
			}
			set
			{
				if ((this._usuario != value))
				{
					this.OnusuarioChanging(value);
					this.SendPropertyChanging();
					this._usuario = value;
					this.SendPropertyChanged("usuario");
					this.OnusuarioChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_senha", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string senha
		{
			get
			{
				return this._senha;
			}
			set
			{
				if ((this._senha != value))
				{
					this.OnsenhaChanging(value);
					this.SendPropertyChanging();
					this._senha = value;
					this.SendPropertyChanged("senha");
					this.OnsenhaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_pessoa", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int id_pessoa
		{
			get
			{
				return this._id_pessoa;
			}
			set
			{
				if ((this._id_pessoa != value))
				{
					if (this._tb_pessoa.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Onid_pessoaChanging(value);
					this.SendPropertyChanging();
					this._id_pessoa = value;
					this.SendPropertyChanged("id_pessoa");
					this.Onid_pessoaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Perfil", DbType="VarChar(100)")]
		public string Perfil
		{
			get
			{
				return this._Perfil;
			}
			set
			{
				if ((this._Perfil != value))
				{
					this.OnPerfilChanging(value);
					this.SendPropertyChanging();
					this._Perfil = value;
					this.SendPropertyChanged("Perfil");
					this.OnPerfilChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tb_pessoa_tb_usuario", Storage="_tb_pessoa", ThisKey="id_pessoa", OtherKey="id_pessoa", IsForeignKey=true)]
		public tb_pessoa tb_pessoa
		{
			get
			{
				return this._tb_pessoa.Entity;
			}
			set
			{
				tb_pessoa previousValue = this._tb_pessoa.Entity;
				if (((previousValue != value) 
							|| (this._tb_pessoa.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._tb_pessoa.Entity = null;
						previousValue.tb_usuario = null;
					}
					this._tb_pessoa.Entity = value;
					if ((value != null))
					{
						value.tb_usuario = this;
						this._id_pessoa = value.id_pessoa;
					}
					else
					{
						this._id_pessoa = default(int);
					}
					this.SendPropertyChanged("tb_pessoa");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tb_venda")]
	public partial class tb_venda : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id_venda;
		
		private System.Nullable<decimal> _valor;
		
		private System.Nullable<decimal> _desconto;
		
		private System.Nullable<decimal> _valor_pago;
		
		private System.Nullable<int> _id_pessoa;
		
		private string _Data;
		
		private System.Nullable<int> _id_pessoaVendedor;
		
		private string _ModePagamento;
		
		private string _Pendente;
		
		private EntitySet<tb_itens_venda> _tb_itens_venda;
		
		private EntityRef<tb_pessoa> _tb_pessoa;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onid_vendaChanging(int value);
    partial void Onid_vendaChanged();
    partial void OnvalorChanging(System.Nullable<decimal> value);
    partial void OnvalorChanged();
    partial void OndescontoChanging(System.Nullable<decimal> value);
    partial void OndescontoChanged();
    partial void Onvalor_pagoChanging(System.Nullable<decimal> value);
    partial void Onvalor_pagoChanged();
    partial void Onid_pessoaChanging(System.Nullable<int> value);
    partial void Onid_pessoaChanged();
    partial void OnDataChanging(string value);
    partial void OnDataChanged();
    partial void Onid_pessoaVendedorChanging(System.Nullable<int> value);
    partial void Onid_pessoaVendedorChanged();
    partial void OnModePagamentoChanging(string value);
    partial void OnModePagamentoChanged();
    partial void OnPendenteChanging(string value);
    partial void OnPendenteChanged();
    #endregion
		
		public tb_venda()
		{
			this._tb_itens_venda = new EntitySet<tb_itens_venda>(new Action<tb_itens_venda>(this.attach_tb_itens_venda), new Action<tb_itens_venda>(this.detach_tb_itens_venda));
			this._tb_pessoa = default(EntityRef<tb_pessoa>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_venda", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id_venda
		{
			get
			{
				return this._id_venda;
			}
			set
			{
				if ((this._id_venda != value))
				{
					this.Onid_vendaChanging(value);
					this.SendPropertyChanging();
					this._id_venda = value;
					this.SendPropertyChanged("id_venda");
					this.Onid_vendaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_valor", DbType="Decimal(15,2)")]
		public System.Nullable<decimal> valor
		{
			get
			{
				return this._valor;
			}
			set
			{
				if ((this._valor != value))
				{
					this.OnvalorChanging(value);
					this.SendPropertyChanging();
					this._valor = value;
					this.SendPropertyChanged("valor");
					this.OnvalorChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_desconto", DbType="Decimal(15,2)")]
		public System.Nullable<decimal> desconto
		{
			get
			{
				return this._desconto;
			}
			set
			{
				if ((this._desconto != value))
				{
					this.OndescontoChanging(value);
					this.SendPropertyChanging();
					this._desconto = value;
					this.SendPropertyChanged("desconto");
					this.OndescontoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_valor_pago", DbType="Decimal(15,2)")]
		public System.Nullable<decimal> valor_pago
		{
			get
			{
				return this._valor_pago;
			}
			set
			{
				if ((this._valor_pago != value))
				{
					this.Onvalor_pagoChanging(value);
					this.SendPropertyChanging();
					this._valor_pago = value;
					this.SendPropertyChanged("valor_pago");
					this.Onvalor_pagoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_pessoa", DbType="Int")]
		public System.Nullable<int> id_pessoa
		{
			get
			{
				return this._id_pessoa;
			}
			set
			{
				if ((this._id_pessoa != value))
				{
					if (this._tb_pessoa.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Onid_pessoaChanging(value);
					this.SendPropertyChanging();
					this._id_pessoa = value;
					this.SendPropertyChanged("id_pessoa");
					this.Onid_pessoaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Data", DbType="VarChar(50)")]
		public string Data
		{
			get
			{
				return this._Data;
			}
			set
			{
				if ((this._Data != value))
				{
					this.OnDataChanging(value);
					this.SendPropertyChanging();
					this._Data = value;
					this.SendPropertyChanged("Data");
					this.OnDataChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_pessoaVendedor", DbType="Int")]
		public System.Nullable<int> id_pessoaVendedor
		{
			get
			{
				return this._id_pessoaVendedor;
			}
			set
			{
				if ((this._id_pessoaVendedor != value))
				{
					this.Onid_pessoaVendedorChanging(value);
					this.SendPropertyChanging();
					this._id_pessoaVendedor = value;
					this.SendPropertyChanged("id_pessoaVendedor");
					this.Onid_pessoaVendedorChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ModePagamento", DbType="VarChar(100)")]
		public string ModePagamento
		{
			get
			{
				return this._ModePagamento;
			}
			set
			{
				if ((this._ModePagamento != value))
				{
					this.OnModePagamentoChanging(value);
					this.SendPropertyChanging();
					this._ModePagamento = value;
					this.SendPropertyChanged("ModePagamento");
					this.OnModePagamentoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Pendente", DbType="NChar(10)")]
		public string Pendente
		{
			get
			{
				return this._Pendente;
			}
			set
			{
				if ((this._Pendente != value))
				{
					this.OnPendenteChanging(value);
					this.SendPropertyChanging();
					this._Pendente = value;
					this.SendPropertyChanged("Pendente");
					this.OnPendenteChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tb_venda_tb_itens_venda", Storage="_tb_itens_venda", ThisKey="id_venda", OtherKey="id_venda")]
		public EntitySet<tb_itens_venda> tb_itens_venda
		{
			get
			{
				return this._tb_itens_venda;
			}
			set
			{
				this._tb_itens_venda.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tb_pessoa_tb_venda", Storage="_tb_pessoa", ThisKey="id_pessoa", OtherKey="id_pessoa", IsForeignKey=true)]
		public tb_pessoa tb_pessoa
		{
			get
			{
				return this._tb_pessoa.Entity;
			}
			set
			{
				tb_pessoa previousValue = this._tb_pessoa.Entity;
				if (((previousValue != value) 
							|| (this._tb_pessoa.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._tb_pessoa.Entity = null;
						previousValue.tb_venda.Remove(this);
					}
					this._tb_pessoa.Entity = value;
					if ((value != null))
					{
						value.tb_venda.Add(this);
						this._id_pessoa = value.id_pessoa;
					}
					else
					{
						this._id_pessoa = default(Nullable<int>);
					}
					this.SendPropertyChanged("tb_pessoa");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_tb_itens_venda(tb_itens_venda entity)
		{
			this.SendPropertyChanging();
			entity.tb_venda = this;
		}
		
		private void detach_tb_itens_venda(tb_itens_venda entity)
		{
			this.SendPropertyChanging();
			entity.tb_venda = null;
		}
	}
}
#pragma warning restore 1591
